sudo: false
dist: trusty

language: java
jdk:
  - oraclejdk8

services: mongodb

addons:
 apt:
  sources:
    - deadsnakes
  packages:
    - python3

before_install:
  - cd $TRAVIS_BUILD_DIR

before_script:
  - chmod +x gradlew

  # Install newest pitest version
  - git clone https://github.com/hcoles/pitest $TRAVIS_BUILD_DIR/pitest
  - mvn -f $TRAVIS_BUILD_DIR/pitest/pom.xml install


  # Copying test-config and set them for travis build
  - cp -f $TRAVIS_BUILD_DIR/src/test/resources/test-configurations/test-config-base.json  $TRAVIS_BUILD_DIR/src/test/resources/test-configurations/test-config.json
  - sed -ri "s|TRAVIS_BUILD_DIR|$TRAVIS_BUILD_DIR|" $TRAVIS_BUILD_DIR/src/test/resources/test-configurations/test-config.json
  - cat $TRAVIS_BUILD_DIR/src/test/resources/test-configurations/test-config.json

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew javadoc
  - ./.utility/push_javadoc_to_gh_pages.sh