sudo: false
dist: trusty

language: java
jdk:
  - oraclejdk8

services: mongodb

addons:
 apt:
  sources:
    - deadsnakes
  packages:
    - python3

before_install:
  - cd $TRAVIS_BUILD_DIR

  # Install jshark for smartshark filer and changesetloader
  - git clone https://github.com/smartshark/jSHARK $TRAVIS_BUILD_DIR/jSHARK
  - ./gradlew install -b $TRAVIS_BUILD_DIR/jSHARK/build.gradle

  # Install bugifxclassifier for mutationdatacollector
  - git clone https://github.com/ftrautsch/BugFixClassifier $TRAVIS_BUILD_DIR/BugFixClassifier
  - ./gradlew install -b $TRAVIS_BUILD_DIR/BugFixClassifier/build.gradle

before_script:
  - chmod +x gradlew

  # Copying test-config and set them for travis build
  - cp -f $TRAVIS_BUILD_DIR/src/test/resources/test-configurations/test-config-base.json  $TRAVIS_BUILD_DIR/src/test/resources/test-configurations/test-config.json
  - sed -ri "s|TRAVIS_BUILD_DIR|$TRAVIS_BUILD_DIR|" $TRAVIS_BUILD_DIR/src/test/resources/test-configurations/test-config.json
  - cat $TRAVIS_BUILD_DIR/src/test/resources/test-configurations/test-config.json

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew javadoc
  - ./.utility/push_javadoc_to_gh_pages.sh